### ISSUE TITLE
2.x Go-Live Punchlist

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmOS.org#23]
Here is the definitive list of tasks to going live with the new farmOS.org!

## Prepare

- [x] General
  - [x] Add `v1.farmos.org` DNS A records pointing to GitHub Pages (clone existing A records).
  - [x] Set `farmOS.org` DNS A record TTL to 30 seconds (at least 24 hours before the switch)
  - [x] Configure Netlify to serve farmos.org, www.farmos.org, docs.farmos.org, v2.farmos.org
- [x] [farmOS.org-EXPERIMENTAL](https://github.com/farmOS/farmos.org-EXPERIMENTAL) (this repo)
  - [x] #12 
  - [x] Menu tweaks
      - [x] Fix Matrix & Discourse links
      - [x] Change "farmOS.js Docs" to just "farmOS.js" (in source repo) 
      - [x] Change "farmOS.py Docs" to just "farmOS.py" (in source repo)
  - [x] Homepage tweaks
      - [x] Update screenshot
      - [x] Remove "Home"
      - [x] Remove TOC
      - [x] Add text and link to https://v1.farmos.org
      - [x] Remove "Quick Links"
      - [x] Review broken links (eg, `/guide`, `/faq`, etc)
  - [x] Change "farmOS 2.x Docs" to "farmOS" in header/`<title>`, etc
  - [x] Remove `/community/farms/` (from farmOS source repo)
  - [x] Monthly Call
      - [x] Create call link and redirect: /community/monthly-call/join -> meet.jit.si/farmos-community
      - [x] Update 2022 call schedule
  - [x] Add `/sitemap.xml`
  - [x] Google Analytics (install Gatsby plugin, use this tracking ID: `UA-56974603-1`)
  - [x] Redirects
      - [x] Review all current paths. Create redirects for any that do not have path in the new site.
      - [x] Set up a general redirect for `docs.farmos.org` => `farmos.org` (https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects)
      - [x] Temporarily redirect `/guide/*` to `https://v1.farmos.org/guide/*` (until v2 guide is available).
- [x] [farmOS.org](https://github.com/farmOS/farmos.org) (old repo)
  - [x] https://github.com/farmOS/farmOS.org/issues/115
  - [x] Review/close/transfer old issues to new repo
  - [x] Merge `7.x-1.x` branch into farmOS `7.x-1.x` (with `-ours` strategy, same as https://www.drupal.org/project/farm/issues/3162606)
  - [x] Move to https://github.com/farmOS-legacy/farmOS.org
- [x] [farmOS.org-EXPERIMENTAL](https://github.com/farmOS/farmos.org-EXPERIMENTAL) (this repo)
  - [x] Move to https://github.com/farmOS/farmos.org

## Deploy

- [x] Point `farmos.org` and `docs.farmos.org` DNS A records to Netlify IPs (remove existing records)
- [x] [farmOS.org](https://github.com/farmOS/farmos.org) (old repo)
  - [x] Change `CNAME` to `v1.farmos.org`: https://github.com/farmOS/farmOS.org/blob/7.x-1.x/docs/CNAME
  - [x] Configure GitHub Pages to host https://v1.farmos.org

**Comment by jgaehring** [comment]
> Review broken links (eg, `/guide`, `/faq`, etc)

I just went ahead and removed these for now (deebd75), but we can still revisit this before launch.

**Comment by jgaehring** [comment]
Ok, I think I've gotten as far as I can on my own with this checklist. I've also provided a rudimentary README (#19), closed #17, and removed #18 from the beta milestone. So all that remains is what's listed above!

If someone else wants to update the screenshot, please be my guest. My local server is not very up-to-date, and I couldn't log on to test.farmos.dev for some reason.

Perhaps we can review the remaining items as a team next week.

**Comment by jgaehring** [comment]
Err maybe not. Something seems to have broken at 7a22e1e, which is causing all pages from other source repos to turn up 404's in production. Womp.

**Comment by jgaehring** [comment]
> Something seems to have broken at 7a22e1e, which is causing all pages from other source repos to turn up 404's in production.

Well, that was a silly mistake. I fixed and rebased on 7cceaa8 so the whole history back to then should be working now. Not something I'd like to see happen normally, but I was moving a little too fast on the `main` branch. Should be stable now, and I'll make sure to develop on another branch or my own fork from here on out.

**Comment by mstenta** [comment]
I spun this off as a follow-up: #30

**Comment by mstenta** [comment]
Done! https://farmOS.org
