### ISSUE TITLE
Anchor links point to the wrong location

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS.org#31]
Not sure this is the right place for this, sorry if it is not.

The anchor links (links referring to the same page) in farmOS.org don't seem to be working correctly. For example on the migration page [https://farmos.org/hosting/migration/](url) the link to "limitations" points back to the main page. [https://farmos.org/#limitations](url). The markdown in the documentation looks right with my limited knowledge so the problem probably lies where it is getting converted to html.

**Comment by mstenta** [comment]
Oh good find @botlfarm! That's interesting. It looks like the anchor links in the right-hand nav bar DO work... it's just the anchor links in content that are broken. I imagine this is related to some of the Gatsby logic for making all the links work together across the various repository sources - does that sound right @jgaehring ?

**Comment by jgaehring** [comment]
Huh, I'm not sure if I'm seeing this. For me, the link to the "Limitations" section is https://farmos.org/hosting/migration/#limitations, not https://farmos.org/#limitations. There is a known issue with the scroll position, but that doesn't sound like what you're describing.

Can you confirm, @botlfarm, that the link circled below is the one you are clicking?

![limitations](https://user-images.githubusercontent.com/5556545/148231476-e3a2f7a1-469b-49e4-9f6d-f28868fb2202.png)

Or is there a link from another page that is directing you to https://farmos.org/#limitations?

**Comment by botlfarm** [comment]
That link works for me just fine. It is the link in the body of the page. See picture below.

![Screenshot_20220105-091732.png](https://user-images.githubusercontent.com/54162154/148232382-9258a4fb-f920-488d-a1df-f9d6deb9d461.png)

**Comment by jgaehring** [comment]
Oh, nevermind, I found it. You're talking about the links in the body text, as in the "Important considerations" section, correct? Like this one:

https://farmos.org/hosting/migration/#:~:text=See%20Limitations%20below.

Yep, definitely a bug. This is an edge case I hadn't considered. The markdown is simply using `#limitations` as its link. Should be simple enough to add a check for any href's that begin with `#`.

Thanks for reporting!

**Comment by jgaehring** [comment]
Alright, this should be resolved, but if there's anything else, please let me know.

Thanks again, @botlfarm!
