### ISSUE TITLE
Link to farmOS demo site

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS.org#43]
As shared here on the forum I've created a site for building demos of farmOS: https://farmos.discourse.group/t/farmos-demo-site/1170 It's been live for almost a month now and has had at least 1 demo created each day. There were a few bugs in the beginning but they have been fixed so it seems to be running better now.

Opening this issue to propose adding a link to the demo site on farmOS.org and collect any blockers/ideas/improvements we should consider before doing so. Perhaps we could also talk about this on the April 13 monthly call
![Screenshot from 2022-04-05 14-21-13](https://user-images.githubusercontent.com/3116995/161852379-21c95819-6d79-4a9d-af05-b9578cde6ade.png)

**Comment by mstenta** [comment]
+1!
