### ISSUE TITLE
Difficulty importing animals

### ISSUE THREAD

**Issue by megandalster** [farmOS/farmOS.org#56]
I have a new localhost FarmOS installation under MAMP and PHP 7.1.  I have mapped a few fields on the farm and everything looks good with Geo mapping.   So I am now trying to import a few animal records that I exported from FarmData and reformatted into a CSV, using your import template.  This import fails with the following error messages:  
<img width="764" alt="Screen Shot 2019-07-23 at 7 06 04 PM" src="https://user-images.githubusercontent.com/4589017/61754277-8a58b800-ad80-11e9-8618-1e440126a607.png">
I am logged into FarmOS as a Farm Manager.  Is there something wrong with my Drupal installation?  Many thanks for any advice you can provide.

**Comment by mstenta** [comment]
Hi @megandalster - take a look at this issue, I believe it's the same: https://github.com/farmOS/farmOS/issues/168

> So I am now trying to import a few animal records that I exported from FarmData and reformatted into a CSV, using your import template.

Exciting! I'm curious to hear how this goes!

PS: We have a new farmOS community forum at https://farmOS.discourse.group if you want to start a conversation about FarmData - could be really useful for people who are using that!

**Comment by megandalster** [comment]
Thanks!  I now have the animal records moved over to FarmOS from FarmData.  

I'm now trying to import Feed Purchases from FarmData.  Your CSV template accommodates only a few fields, but my download has a lot more data -- for example, vendor, unit, unit_price, unit_weight. Is there a way in FarmOS to modify the CSV upload template to accommodate these additional fields.  I see these fields in the headers on your Purchases page. 

Thanks for the suggestion.  I will start a conversation about FarmData on your community forum as soon as I have a little more confidence with the data download-upload process.
